name: novapay

services:
  postgres:
    image: postgres:18-alpine
    container_name: payment-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: payments
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payment_user -d payments"]
      interval: 5s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:3.8
    container_name: payment-localstack
    restart: unless-stopped
    ports:
      - "4566:4566"
    environment:
      SERVICES: sns,sqs,dynamodb
      DEBUG: 0
      AWS_DEFAULT_REGION: us-east-1
    volumes:
      - localstack_data:/var/lib/localstack
      - ./localstack-init:/etc/localstack/init/ready.d:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  localstack_data:
